### ISSUE TITLE
Explicit end needed for anonymous functions

### ISSUE THREAD

**Issue by seaneshbaugh** [nurugger07/calliope#47]
So I was trying to make some forms in a Phoenix application using phoenix_haml/Calliope and I ran into some problems.

First, what I ultimately want to produce is something equivalent to this:

```html 
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
    <label for="page[title]">Title</label>
    <%= text_input f, :title, class: "form-control" %>
  </div>
  <div class="form-group">
    <label for="page[body"]>Body</label>
    <%= textarea f, :body, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>
```

And here's what I had to do in order to get it working:

```haml
= form_for @changeset, @action, fn f ->
  .form-group
    %label{ for: "page[title]" }
      Title
    = text_input f, :title, class: "form-control"
  .form-group
    %label{ for: "page[body]" }
      Body
    = textarea f, :body, class: "form-control"
  .form-group
    = submit "Submit", class: "btn btn-primary"
- end
```

Initially I had tried this:

```haml
- form_for @changeset, @action, fn f ->
```

but I found that the compiler was treating everything inside the anonymous function as if it were Elixir instead of HAML. As you can imagine this causes all sorts of mysterious and obtuse errors. I believe it was this pull request: https://github.com/nurugger07/calliope/pull/40, that introduced that functionality.

After playing around with the compiler I was able to determine that the issue with the output had to do with with this line:

```elixir
Regex.match? ~r/(fn )|(fn\()[a-zA-Z0-9,\) ]+->/, script ->
```

My understanding is that the parser translates `-` into `:smart_script` which gets evaluated differently from a regular `script`. Regular scripts don't add the closing `<% end %>` so it's necessary to add it manually in this particular case.

I was able to come up with something of a fix for this whole thing. By adding this:

```elixir
Regex.match? ~r/(fn [a-zA-Z0-9,\) ]+=>)|(fn\()[a-zA-Z0-9,\) ]+=>/, script ->
  %{cmd: String.replace(script, ~r/=>$/, "->"), wraps_end: "<% end %>", end_tag: "%>", open_tag: "<%="}
```

before the previously mentioned `cond` match I was able to make it so that smart scripts which ended an anonymous function that use a `=>` were treated correctly as HAML and correctly wrapped the end tag (note: the fat arrow gets replaced so the resulting EEX is good). The existing functionality for smart scripts didn't appear to be impacted.

Rather than submit a pull request I figured I'd open an issue to make this known. I'm aware there's already some non-standard stuff in Calliope as a matter of necessity. Adding more without a really good reason seems less than ideal. But on the flip side; having to explicitly add an `end` statement is already non-standard HAML.

Either way I suggest that the documentation be updated to explain the need for using `-` and adding a closing `end` manually since I imagine I won't be the only person to run into this. Without first really digging into the parser and compiler the error messages that Elixir produces for this are worse than useless.

**Comment by nurugger07** [comment]
The `=` is meant for scripts that the result is output and `-` is for scripts that just execute. You are correct to use the `=` to output the result of the `form_for` but the `- end` isn't needed. However, I will test this to make sure that the code is being executed correctly.

**Comment by cblavier** [comment]
Same issue here.
Adding ```- end```solved it!

**Comment by smpallen99** [comment]
Fixed. Should not require an end now.

**Comment by samueljseay** [comment]
Can I ask, is this in a released version of Calliope? afaict using phoenix_haml which relies on Calliope 0.3.0 this is still an issue?
